# Generated by Django 4.2.4 on 2023-08-27 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_short_description', models.CharField(max_length=300, verbose_name='Введите краткое описание задачи')),
                ('todo_full_description', models.CharField(max_length=300, verbose_name='Полное описание задачи')),
                ('todo_date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('todo_start_date', models.DateField(verbose_name='Дата начала задачи')),
                ('todo_start_time', models.TimeField(verbose_name='Время начала задачи')),
                ('todo_status', models.BooleanField(default=False, verbose_name='Статус выполнения задачи')),
                ('todo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
